[package]
name = "minlp"
version = "0.1.0"
authors = ["Gregory <greg.henselman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

minilp = "0.2.2"

